### ISSUE TITLE
Change the use of Exclamation and Question mark together in "Help!?"

### ISSUE THREAD

**Issue by iprithvitharun** [TomTasche/OpenDocument.droid#154]
Using question mark and an exclamation point together shows a level of surprise combined with emotion which is used only in casual and informal writing. 

Also, it's odd. It doesn't sound like a statement that can help users. It creates a sense of doubt before clicking which shouldn't be the case before clicking for help.

![IMG_20200131_133548](https://user-images.githubusercontent.com/58725708/73522570-b7bca780-442e-11ea-85fd-0a2ee8b37098.jpg)

**Comment by iprithvitharun** [comment]
@TomTasche I can work on this.

**Comment by TomTasche** [comment]
Thanks for submitting this issue! I'd love to accept a pull request for your change.

**Comment by iprithvitharun** [comment]
Changes merged.
