### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by Joseph-PS** [TomTasche/OpenDocument.droid#156]
![Screenshot_20200204-013553](https://user-images.githubusercontent.com/60518474/73687226-94744f80-46ef-11ea-8f48-bde6f006b1ae.jpg)

Suggesting users to use another app to open the document goes against the main purpose of the app. 
Also, it doesn't sound like a statement that helps the user inside the app rather forcing the user out of the application.

**Comment by Joseph-PS** [comment]
@TomTasche I'd like to work on this.

**Comment by TomTasche** [comment]
For some files it does make sense to open it in another app, i.e. for a calendar entry or similar. I agree that our communication with the user is not great though. I'd be happy to accept a pull request for this!

**Comment by Joseph-PS** [comment]
PR #157 merged.
