### ISSUE TITLE
Attach an APK in the release section

### ISSUE THREAD

**Issue by Poussinou** [TomTasche/OpenDocument.droid#165]
Since we can't include this app in F-Droid, would it be possible to provide an apk in the release section, for people without google play store?

**Comment by TomTasche** [comment]
Good idea! There you go: https://github.com/TomTasche/OpenDocument.droid/releases/tag/3.2.5

**Comment by EdoSecco** [comment]
Hi,
I use [Obtainium](https://github.com/ImranR98/Obtainium) and by chance noticed that you published the apk only until 3.3.2

Thank you!
