### ISSUE TITLE
Open document via ownCloud

### ISSUE THREAD

**Issue by jancborchardt** [TomTasche/OpenDocument.droid#65]
Currently it’s possible to open documents from some external apps through the »Open document via« dialog. This includes ES File Explorer and Dropbox.

It would be cool if the ownCloud Android app could be supported as well. Anything that needs to be done on the side of the app to enable that? The app is completely open source as well: https://github.com/owncloud/android

(This would be especially cool since ownCloud has a WebODF app called »Documents« since the last version. That allows you to view and edit ODTs online, collaborative as well similar to Etherpad.)

**Comment by TomTasche** [comment]
this should be "fixed" now as we register for all kinds of file types now. that was necessary to support apps like "Samsung My Files"

**Comment by jancborchardt** [comment]
Cool stuff, thanks for the update @TomTasche! :) We’re Nextcloud now, and it should work with that too then automatically if it uses a standard method.
