### ISSUE TITLE
Error:Execution failed for task ':app:processDebugGoogleServices'.

### ISSUE THREAD

**Issue by abhi08singh** [TomTasche/OpenDocument.droid#72]
Hi, 
I am getting this error for the very first time when I am going to build the project.

>Error:Execution failed for task ':app:processDebugGoogleServices'.
 File google-services.json is missing. The Google Services Plugin cannot function without it. 
 Searched Location: 
  /home/app/Downloads/OpenDocument.droid-master/app/src/debug/google-services.json
  /home/app/Downloads/OpenDocument.droid-master/app/google-services.json

Please provide me some solution.

**Comment by TomTasche** [comment]
You can create your own Firebase project on firebase.google.com and get the file from there. It is just used by our app to communicate with Firebase.
