### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by mayowadavid** [TomTasche/OpenDocument.droid#74]
Hello, @TomTasche I came across this wonder Opendocument reader while i was checking for an application that will make it easier for a much faster access to read any open document easily. I found your application and there was never a regret ever since i have been using the application. I thought to contribute by creating a logo that will help portray the value of the application. I came up with this.

![Open-Document-Reader-500edit.png](https://steemitimages.com/DQmdBZkQ76gU61hUmmQa6C1gsF45UiMryJwLWhE8Kj8gPbB/Open-Document-Reader-500edit.png)
***
***
![Monochrome-version-opendocument.png](https://steemitimages.com/DQmeBL1CzVzm1yoDvU72kGHKeGmdHjXaR8yv8AYaJYNJ4F9/Monochrome-version-opendocument.png)

The link to png and edited file can be found [Here](https://drive.google.com/folderview?id=1LdkCvzOrFz_-uMh_Ejzf4UJggq8PISqF)

**Comment by TomTasche** [comment]
hey david,

thanks so much for contributing to this project! this is exactly the reason why we decided to make this project open-source :smiley: 

in order to make your icon the default for this project, i'd like to see a version that follows the material design principles more: https://material.io/design/iconography/ - for example, as far as i understood material design icons are meant to be flat and have no shadows!

in any case, thanks for your effort again!

**Comment by mayowadavid** [comment]
Ok sir i will work on it

**Comment by mayowadavid** [comment]
### @TomTasche 
### Here is **144 dpi view**
![open-document-reader-144-1](https://user-images.githubusercontent.com/34623610/40436603-3be69586-5eab-11e8-86f7-011ef8490281.png)
***
### **176dpi preview**
![open-document-reader-176-1](https://user-images.githubusercontent.com/34623610/40436552-173c5f0e-5eab-11e8-8fdd-124ea9ce7afe.png)
***

### After making adjustment based on material design principle.

**Comment by mayowadavid** [comment]
@TomTasche Is there any other thing you think need to be done?

**Comment by mayowadavid** [comment]
@TomTasche 

Here is a preview of 48 *48 px
![open-document-reader-mdpi](https://user-images.githubusercontent.com/34623610/40549710-1c4391f8-6030-11e8-80b7-6133e0d5c4df.png)
***
72*72 px
![open-document-reader-hdpi](https://user-images.githubusercontent.com/34623610/40549772-41e04816-6030-11e8-85f2-907bdff20157.png)
***
96*96 px
![open-document-reader-xhdpi](https://user-images.githubusercontent.com/34623610/40549799-5094a9d8-6030-11e8-9fae-a28fc239e36b.png)

**Comment by mayowadavid** [comment]
@TomTasche 
The shadow behind the file is for lightning study which was also used in gmail icon.

**Comment by mayowadavid** [comment]
@TomTasche
